config 모듈 제작
fdcl-ftc/fault-tolerant-control pull request #101
Opened 2021-07-17 04:55 UTC by seong-hun

Resolves #86 

- [x] 랜덤 값을 파일로 저장하고 불러오는 방식으로 변경
    - [ ] 데이터 파일은 구글드라이브에서 공유
- [x] 실험을 위한 Default configuration 및 env 파일 분배
- [x] 선형최적 제어기를 이용해 테스트 작성

마음대로 만들어봄 ㅎㅎ

데이터 파일을 구글 드라이브에서 공유하는 것은 제가 뭔가를 할 필요는 없어 보여서 내버려 뒀습니다.

## 기본 사용법

전체 파라미터 값을 `ftc/config.py`에서 관리할 수 있게끔 만들었습니다.

예를 들어서 각 모듈에서 어떤 파라미터를 정해서 쓰고 싶다고 하면 모듈 안에서 그냥 클래스 어트리뷰트 등으로 만들거나 해서 써도 되지만
다음과 같이 써도 되게끔 만들었습니다.

`ftc/path/to/module/moduleA.py` 에서:
```python
import ftc.config

cfg = ftc.config.load(__name__)

class MyClass:
    def __init__(self):
        self.attr1 = cfg.attr1
```

`ftc/config.py` 에서:
```python
default_settings = fym.parser.parse({
    # :::::: FTC Modules :::::: #

    "path.to.module.moduleA": {
        "attr1": "this is attr1",
    }
}
```

## Configuration 변경

기본 config와 다른 값을 쓰고 싶다고 한다면 다음과 같이 직접 할당해서 바꿀 수 있습니다.

```python
cfg = ftc.config.load()

cfg.models.multicopter.init.pos = np.random.rand(3, 1)
```

혹은 `config.set` 메소드를 쓰면 한 번에 여러 변수들을 바꿀 수 있습니다.

```python
ftc.config.set({
    "cfg.models.multicopter": {
        "init.vel": np.random.rand(3, 1),
        "mixer.type": "hexa-+",
    }
})  
```

## 저장하기

config 저장은 그냥 아무렇게나 하면 됩니다.

```python
def run():
    env = Env()
    env.logger = fym.Logger("data.h5")
    env.logger.set_info(cfg=ftc.config.load())

    env.reset()

    while True:
        # ...
```

2021-07-19 04:54 UTC, hnlee77 commented
제가 생각했던 방식과 매우 비슷하면서 엄청 깔끔하네요! 감사합니다.

2021-07-19 09:31 UTC, hnlee77 requested changes

2021-07-19 09:31 UTC, hnlee77 commented on ftc/agents/switching.py
> +from loguru import logger
얘는 왜 사용하는 거에요? 어떤 아래의 debug 같은 기능을 사용하기 위함인가요??

2021-07-19 09:31 UTC, hnlee77 commented on ftc/agents/switching.py
> +            B = jacob_analytic(deriv, 1)(xtrim, utrim)[:, :, 0]
이거 왜 이렇게 바꾼거에요? 오류가 나는 것 같은데 확인 부탁드려요.

2021-07-20 05:40 UTC, seong-hun commented on ftc/agents/fdi.py
> +cfg = ftc.config.load(__name__)
넵

2021-07-20 05:41 UTC, seong-hun commented on ftc/agents/switching.py
> +        logger.debug("LQR table keys: {}", keys)
python 기본 모듈인 logger의 확장판?인 [loguru](https://loguru.readthedocs.io/en/stable/) 모듈입니다~ 사용법은 링크에 상세히 나와 있슴다~

2021-07-20 05:42 UTC, seong-hun commented on ftc/models/multicopter.py
> +
이태영 교수님 파라미터를 쓰느냐, Falconi 파라미터를 쓰느냐에 따라 달라져서요!

2021-07-20 05:42 UTC, seong-hun commented on ftc/agents/switching.py
> +from loguru import logger
넵

2021-07-20 05:43 UTC, seong-hun commented on ftc/agents/switching.py
> +            B = jacob_analytic(deriv, 1)(xtrim, utrim)[:, :, 0]
나는 저렇게 해야 오류가 안나던데??

2021-07-20 05:43 UTC, seong-hun commented on ftc/models/multicopter.py
>  from fym.utils.rot import dcm2quat, quat2dcm, angle2quat, quat2angle
이런식이 뭐예요?

2021-07-20 05:43 UTC, seong-hun commented on ftc/models/multicopter.py
>  from fym.utils.rot import dcm2quat, quat2dcm, angle2quat, quat2angle
모듈 import 말하는건가? 이런걸로 느려지진 않죠...

2021-07-20 06:34 UTC, seong-hun commented on ftc/agents/switching.py
> +            B = jacob_analytic(deriv, 1)(xtrim, utrim)[:, :, 0]
numdifftools 버전 확인 바랍니다

2021-07-20 06:42 UTC, hnlee77 commented on ftc/models/multicopter.py
> +
애초에 config로 부터 이태영 교수님 파라미터를 쓰느냐, Falconi 파라미터를 쓰느냐를 결정하게 되는 거 아닌가요??

2021-07-20 06:46 UTC, seong-hun commented on ftc/models/multicopter.py
> +
맞긴한데.. ㅋㅋ config에서 불러와도 되는데요, 굳이 쓸데 없는 if 문들이 필요할 것 같은데.. 제안사항이 있나요?

2021-07-20 06:56 UTC, hnlee77 commented on ftc/agents/switching.py
> +            B = jacob_analytic(deriv, 1)(xtrim, utrim)[:, :, 0]
오 업데이트 하니 잘 됩니다 ㅎㅎ

2021-07-20 07:09 UTC, seong-hun commented on test/scenario_a_2.py
>      exp1_plot()
오 해보겠슴다

2021-07-20 07:15 UTC, seong-hun commented on test/scenario_a_2.py
>      exp1_plot()
? 바로 에러남 ㅋㅋ

2021-07-20 07:16 UTC, seong-hun commented on test/scenario_a_2.py
>      exp1_plot()
plotting 모듈에 대해서 새로 이슈를 파는게 좋아 보입니다

2021-07-20 07:22 UTC, hnlee77 commented on test/scenario_a_2.py
>      exp1_plot()
어떤 에러가 나는 걸까요??

2021-07-20 07:23 UTC, seong-hun commented on test/scenario_a_2.py
>      exp1_plot()
일단 제 코드를 고쳐서 돌아가게끔 해서 올렸습니다~

2021-07-20 07:23 UTC, seong-hun commented on test/scenario_a_2.py
>      exp1_plot()
> 어떤 에러가 나는 걸까요??

이런걸 이슈로 파자는 얘긴데

2021-07-20 07:23 UTC, hnlee77 commented on test/scenario_a_2.py
>      exp1_plot()
오잉 저는 잘되는데..ㅋㅋㅋㅋ

2021-07-20 07:24 UTC, seong-hun commented on test/scenario_a_2.py
>      exp1_plot()
ㅋㅋㅋ 일단 지금 푸쉬한건 돌아갑니다~

2021-07-20 07:24 UTC, seong-hun commented on ftc/models/multicopter.py
> +
이건 개취이므로 닫겠습니다.

2021-07-20 07:34 UTC, hnlee77 commented on ftc/models/multicopter.py
> +
음 그렇겠군요... ㅋㅋㅋ 지금 상태가 알아보기 깔끔하겠어요.. 일단 그대로 두죠!

2021-07-20 07:35 UTC, hnlee77 commented on test/scenario_a_2.py
>      exp1_plot()
> > 어떤 에러가 나는 걸까요??
> 
> 이런걸 이슈로 파자는 얘긴데

아하 그럼 요거를 이슈로 파주시면 감사하겠습니다~

2021-07-20 10:07 UTC, hnlee77 approved these changes

2021-07-21 03:02 UTC, merged