Modify max. rotor thrust
fdcl-ftc/fault-tolerant-control pull request #109
Opened 2021-07-29 04:23 UTC by hnlee77

Resolve #62.

참고문헌 (by @JinraeKim) 대로 maximum rotor 값 변경.
[1] M. C. Achtelik, K. M. Doth, D. Gurdan, and J. Stumpf, “Design of a multi rotor MAV with regard to efficiency, dynamics and redundancy,” AIAA Guid. Navig. Control Conf. 2012, no. August, pp. 1–17, 2012, doi: 10.2514/6.2012-4779.

2021-07-30 03:58 UTC, JinraeKim requested changes

2021-07-30 03:58 UTC, JinraeKim commented on ftc/config.py
> +                "rotor_max": 40 * 0.6371,  # abount m * g
이거 m*g 의 유사치인 40 대신 실제 m*g 값을 넣을수는 없나요?

2021-07-30 06:48 UTC, hnlee77 commented on ftc/config.py
> +                "rotor_max": 40 * 0.6371,  # abount m * g
코드를 수정하다보니.. 함수를 만들어 넣는 것보다, `m*g`값을 가져다가 그냥 넣으면 되는 것이 결국 더 간단한거 아닌가?? 라는 생각이 들어서 그렇게 수정했어요..ㅋㅋㅋ 
혹시 예상되는 다른 문제가 있을까요?

2021-07-30 06:59 UTC, JinraeKim commented
아직 작업중인거라면 draft화 한 뒤 리뷰요청을 하지 말아야할 것 같습니다.
작업중인게 아니고 리뷰를 요청했다면,
아까 둘이 같이 있을 때 얘기한거랑 방향이 다른 것 같은데...

원래 PR 건 커밋이랑 값의 정확도 외엔 차이가 없어보입니다.
m, g 에 종속적이게 만들고, config 파일을 바꿈으로써 rotor max을 조절하기 쉽게 해야하지 않을까요?

2021-07-30 12:14 UTC, hnlee77 commented
> 아직 작업중인거라면 draft화 한 뒤 리뷰요청을 하지 말아야할 것 같습니다.
> 작업중인게 아니고 리뷰를 요청했다면,
> 아까 둘이 같이 있을 때 얘기한거랑 방향이 다른 것 같은데...
> 
> 원래 PR 건 커밋이랑 값의 정확도 외엔 차이가 없어보입니다.
> rotor max 가 m, g 에 종속적이게 만들고, config 파일을 바꿈으로써 rotor max을 조절하기 쉽게 해야하지 않을까요?

리뷰를 요청한게 맞긴 한데요.. [여기](https://github.com/fdcl-ftc/fault-tolerant-control/pull/109#discussion_r679689342)에 답변을 하긴했지만 혹시 안보이나요??
일단 얘기했던 방향 (함수 형태로 m, g를 인자로 받아 rotor max의 dict 값을 뱉도록 수정) 대로 수정을 하던 도중에 'm, g에 종속적인 값으로 만들 필요가 있을까?' 라는 생각이 들었어요. 예를 들어서 다른 모델에서 다른 방식의 rotor_max의 값을 사용한다고 하면 각 rotor_max에 해당하는 여러 함수들을 만들게 될 것 같아서요.
그러니까 결국 
1. 함수의 형태로 m, g에 따라 rotor max가 바뀌도록 값을 지정하고, `config`에 추가 -> 함수 내부에서 계산 방식을 변경.
2. config 파라미터에 직접 m, g 값을 통해 계산하여 지정
의 두가지 중에서 2. 의 방식이 해당하는 모델의 파라미터를 확인 (또는 수정) 하기에 더 직관적이고 간편하지 않은가? 라는 생각에서 이렇게 수정을 했어요. 의견 주세요!

2021-07-31 10:56 UTC, JinraeKim commented
> 리뷰를 요청한게 맞긴 한데요.. [여기](https://github.com/fdcl-ftc/fault-tolerant-control/pull/109#discussion_r679689342)에 답변을 하긴했지만 혹시 안보이나요??

보입니다~

> 일단 얘기했던 방향 (함수 형태로 `m`, `g`를 인자로 받아 rotor max의 dict 값을 뱉도록 수정) 대로 수정을 하던 도중에 '`m`, `g`에 종속적인 값으로 만들 필요가 있을까?' 라는 생각이 들었어요. 예를 들어서 다른 모델에서 다른 방식의 rotor_max의 값을 사용한다고 하면 각 rotor_max에 해당하는 여러 함수들을 만들게 될 것 같아서요.

현재 rotor max 가 m, g에 종속적인 값이니 종속적으로 만들수밖에 없지 않을까요? "다른 모델에서 다른 방식의 rotor_max 를 사용한다면 각 rotor_max 에 해당하는 여러 함수들을 만들게 될 것 같아서요." => 네, 말씀하신대로 하면 될 것 같습니다.

> * 함수의 형태로 `m`, `g`에 따라 rotor max가 바뀌도록 값을 지정하고, `config`에 추가 -> 함수 내부에서 계산 방식을 변경.
> * `config` 파라미터에 직접 `m`, `g` 값을 통해 계산하여 지정
>   의 두가지 중에서 2. 의 방식이 해당하는 모델의 파라미터를 확인 (또는 수정) 하기에 더 직관적이고 간편하지 않은가? 라는 생각에서 이렇게 수정을 했어요. 의견 주세요!

1. 에 대해서는, 함수 내부에서 계산 방식을 변경한다는게 무슨 말인지 모르겠는데... 뭐에 대해 변경을 한다는거죠?
2. 에 대해서는, 코드에서 어떤 값을 참조할 때 "직접 숫자를 넣는 행위"는 부디 피해주셨으면 합니다. 코드를 보고 원래의 의미를 유추하기도 힘들고, 오타 발생 확률도 높고, 만일 질량이나 중력가속도 값의 precision 이 바뀌면 저 코드도 일일이 바꿔야하지 않을까요... 저라면 특별히 어떤 부작용이 예상되지 않더라도 저렇게 짜지는 않을 것 같습니다 (이미 저 자체로 부작용이 예상되긴 하지만...).

2021-08-03 06:49 UTC, hnlee77 commented
> 현재 rotor max 가 m, g에 종속적인 값이니 종속적으로 만들수밖에 없지 않을까요? "다른 모델에서 다른 방식의 rotor_max 를 사용한다면 각 rotor_max 에 해당하는 여러 함수들을 만들게 될 것 같아서요." => 네, 말씀하신대로 하면 될 것 같습니다. 여러 함수를 만드는 것에 혹시 거부감이 있는건가요? 만일 그렇다면, 왜 거부감이 드는지는 잘 이해하지 못하겠습니다.
음.. 이것에 대해서는 처음에 제가 막연하게 생각해보니 `config.py`에 각 rotor_max에 따른 함수들이 여러개 등장한다면 꽤 지저분해지지 않을까 하는 생각이 들었어요..

> 1. 에 대해서는, 함수 내부에서 계산 방식을 변경한다는게 무슨 말인지 모르겠는데... 뭐에 대해 변경을 한다는거죠?
이것은 예를 들어 `taeyoung_lee` 플랜트에 해당하는 rotor_max 함수의 식을 바꾸고자 한다면 결국 함수 내부에서 식을 변경하게 될텐데, 여기에 해당하는 작업과 `config`에서 파라미터의 값을 바꾸는 작업 중에 후자의 경우가 편하지 않을까라는 의미였어요.
 
> 2. 에 대해서는, 코드에서 **_어떤 값을 참조할 때 "직접 숫자를 넣는 행위"는 부디 피해주셨으면_** 합니다 (엄근진). 코드를 보고 원래의 의미를 유추하기도 힘들고, 오타 발생 확률도 높고, 만일 질량이나 중력가속도 값의 precision 이 바뀌면 저 코드도 일일이 바꿔야하지 않을까요... 저라면 특별히 어떤 부작용이 예상되지 않더라도 저렇게 짜지는 않을 것 같습니다 (이미 저 자체로 부작용이 예상되긴 하지만...).
이 내용은 매우 동의합니다. 저도 코드짜는데 있어서 정말 중요한 부분이라고 생각해요. 다시 알려줘서 고맙습니다. 곰곰이 생각해보니 이런 부작용을 제가 놓치고 생각했던 것 같아요. (자꾸 단순하게 파라미터를 변경하는것이 코드를 짜는 입장에서 편하다는 생각에서 벗어나지 못한것 같습니다. 이런 실수는 항상 주의하도록 할게요.). 그래서 결론적으로는 함수헝태로 `m`, `g`에 종속적으로 rotor_max를 짜는 것이 좋은 방향일 것 같아 보입니다.
>    +) 함수가 별로면 그냥 dict["rotor_max"] = 0.6371 * dict["m"] * dict["g"] 이런 식으로 해도 충분할 것 같습니다.
이것도 좋은 제안이네요~ 

다시 수정을 해보도록 하겠습니다.

2021-08-03 06:54 UTC, JinraeKim commented
피드백 감사합니다 ㅎㅎ

2021-08-09 03:14 UTC, hnlee77 commented
수정했는데 확인 한 번 부탁드려요~

2021-08-09 03:30 UTC, JinraeKim commented on ftc/config.py
> +def maximum_thrust(m, g):
```suggestion
def _maximum_thrust(m, g):
```

2021-08-09 03:30 UTC, JinraeKim commented on ftc/config.py
> +def maximum_thrust(m, g):
여기서만 쓰는 함수이니 이렇게 써도 좋을듯 합니다 ㅎㅎ

2021-08-09 03:30 UTC, JinraeKim commented on ftc/config.py
> +                     {"rotor_max": maximum_thrust(m, g)}
```suggestion
                     {"rotor_max": _maximum_thrust(m, g)}
```

2021-08-09 03:30 UTC, JinraeKim commented on ftc/config.py
> +set_maximum_rotor(settings)
```suggestion
_set_maximum_rotor(settings)
```

2021-08-09 03:30 UTC, JinraeKim commented on ftc/config.py
> +def set_maximum_rotor(settings):
```suggestion
def _set_maximum_rotor(settings):
```

2021-08-09 03:37 UTC, hnlee77 commented on ftc/config.py
> +def maximum_thrust(m, g):
꿀팁 감사합니다~

2021-08-09 08:23 UTC, hnlee77 commented
@JinraeKim 반영 완료했습니다~

2021-08-09 08:34 UTC, JinraeKim approved these changes

2021-08-09 08:35 UTC, merged