Add LQR controller example
fdcl-ftc/fault-tolerant-control pull request #133
Opened 2022-08-30 03:52 UTC by hnlee77

Multicopter LQR control 예제파일 추가

2022-08-30 08:04 UTC, hnlee77 commented on ftc/models/LC62.py
> +def safeupdate(*configs):
그게 좋을 것 같습니다. 이 부분은 수정하도록 하겠습니다.

2022-08-30 08:07 UTC, hnlee77 commented on examples/controller_lqr.py
> +        self.K, *_ = fym.agents.LQR.clqr(A, B, Q, R)
아 이부분이 조금 의문인 상황인데요. 실제로 LQR controller를 initialize할 때 (`__init__()`) 저 부분을 넣으려고 했었는데, 지금 `ftc.make(`LQR`)`처럼 사용할 때 인자를 어떻게 넣을 수 있는지 잘 모르겠습니다..ㅠ

2022-08-30 08:34 UTC, seong-hun commented on examples/controller_lqr.py
> +        self.K, *_ = fym.agents.LQR.clqr(A, B, Q, R)
흠 그러게

2022-08-30 09:20 UTC, hnlee77 commented on examples/controller_lqr.py
> +        self.K, *_ = fym.agents.LQR.clqr(A, B, Q, R)
#135 를 통해 해결.

2022-09-16 06:41 UTC, hnlee77 commented
@seong-hun @miaerosae 여기도~

2022-09-16 06:43 UTC, seong-hun commented
#132 와 겹쳐서 보기가 힘드네요..

2022-09-16 06:53 UTC, hnlee77 commented
> #132 와 겹쳐서 보기가 힘드네요..

아하.. 얘는 #132 를 머지한 후에 해야겠군요..

2022-09-20 06:20 UTC, hnlee77 commented
@seong-hun @miaerosae 얘도 리뷰 마저 부탁합니다.

2022-09-20 06:52 UTC, seong-hun commented
기록용으로 결과 그래프 같이 올려주면 좋을 것 같습니다~

2022-09-20 07:37 UTC, hnlee77 commented
결과 그래프 올립니다~

### 결과 그래프
- State responses
![Figure_1](https://user-images.githubusercontent.com/32696021/191196020-2f4a3bc6-b7ed-489f-93a3-50c8f3b69e68.png)

- Generalized forces responses
![Figure_2](https://user-images.githubusercontent.com/32696021/191196073-c5201d58-bda8-4532-8a83-907ccf6126e8.png)

- Rotor thrust responses
![Figure_3](https://user-images.githubusercontent.com/32696021/191196094-411da613-5759-46d3-b4bd-4be0775f82ac.png)

2022-09-20 09:17 UTC, seong-hun requested changes
`ftc/models/multicopter.py` 파일은 따로 풀리퀘를 올리는게 좋을 것 같습니다.

2022-09-20 09:36 UTC, hnlee77 commented
> `ftc/models/multicopter.py` 파일은 따로 풀리퀘를 올리는게 좋을 것 같습니다.

이 풀리퀘에서 삭제하고 #136 으로 올렸습니다~

2022-09-20 09:39 UTC, seong-hun approved these changes

2022-09-20 09:51 UTC, merged