Fix plotframes
fdcl-ftc/fault-tolerant-control pull request #182
Opened 2023-10-06 07:18 UTC by hnlee77

3d animation 보완
- 추력 화살표 추가

2023-10-06 08:17 UTC, hnlee77 commented
@JinraeKim 리뷰 후 기체도 함께 #181 에 반영하시면 되겠습니다!

2023-10-13 07:12 UTC, hnlee77 commented
@JinraeKim 이거 리뷰도 부탁~

2023-10-13 07:58 UTC, JinraeKim commented
> @JinraeKim 이거 리뷰도 부탁~

계속 커밋이 생기길래...

일단 지금 필요한게 아니라면 천천히 봐도 괜찮을까요?

2023-10-13 10:03 UTC, hnlee77 commented
> 계속 커밋이 생기길래...
> 
> 일단 지금 필요한게 아니라면 천천히 봐도 괜찮을까요?

아하 rebase 했어요~ 이제 다시 봐주시면 감사!

2023-10-16 00:42 UTC, JinraeKim commented
@hnlee77 수정 시 실행 결과를 같이 올려주면 좋겠습니다.

아래는 올린 코드로 실행한 결과인데, 고장이 없지만 1쌍의 추력벡터-vertical rotor 가 그려지지 않고 있습니다.

그리고 vertical rotor 와 horizontal rotor 색상 구분이 필요해보입니다.

고장 시 rotor 의 색상을 바꾸는 것도 좋겠습니다.

나머지는 LGTM
![animation](https://github.com/fdcl-ftc/fault-tolerant-control/assets/43136096/1f00a032-c4cd-451c-8f2a-3747e390d805)

2023-10-16 03:20 UTC, hnlee77 commented
네 그러도록 하겠습니다~
고장이 없을 때 저의 경우에는 잘 나오는 것 같습니다..!
![animation](https://github.com/fdcl-ftc/fault-tolerant-control/assets/32696021/a72ae054-9c6a-463e-a961-dce9b1d99a49)

그리고 수평, 수직 로터의 색이 지금 다른 상황이긴 한데 더 명확하게 수정을 원하는 것일까요?
사실 아래 그림과 일치하도록 그린 것이긴 합니다~
![image](https://github.com/fdcl-ftc/fault-tolerant-control/assets/32696021/92f7c22a-c3bb-47bd-acf3-6926c2b9e7bd)

2023-10-16 06:24 UTC, JinraeKim commented
> 고장이 없을 때 저의 경우에는 잘 나오는 것 같습니다..!

신기하네요...
ad8bc93 를 그대로 실행한게 맞나요?



> 사실 아래 그림과 일치하도록 그린 것이긴 합니다~

아 그렇군요. 시각적으로 구분이 잘 안되긴 하는데, 일단 넘어가도 되겠습니다

2023-10-16 06:35 UTC, JinraeKim requested changes

2023-10-16 06:35 UTC, JinraeKim commented on ftc/plotframe.py
> +    uav.ax.set(zlim3d=(posz + uav.zlim[0], posz + uav.zlim[1]), zlabel="Z")
```suggestion
    uav.ax.set(xlim3d=(posx + uav.xlim[0], posx + uav.xlim[1]), xlabel="E")
    uav.ax.set(ylim3d=(posy + uav.ylim[0], posy + uav.ylim[1]), ylabel="N")
    uav.ax.set(zlim3d=(posz + uav.zlim[0], posz + uav.zlim[1]), zlabel="U")
```

2023-10-16 06:35 UTC, JinraeKim commented on ftc/plotframe.py
>          self.ax.set(ylim3d=self.ylim, ylabel="Y")
```suggestion
        self.ax.set(xlim3d=self.xlim, xlabel="E")
        self.ax.set(ylim3d=self.ylim, ylabel="N")
```

2023-10-16 06:35 UTC, JinraeKim commented on ftc/plotframe.py
>          self.ax.set(ylim3d=self.ylim, ylabel="Y")
왜 L111 이 선택이 안 되는지 모르겠는데 그것도 U 로

2023-10-16 06:44 UTC, hnlee77 commented
반영했습니다~

2023-10-16 07:18 UTC, JinraeKim approved these changes

2023-10-16 07:38 UTC, merged