Add active ftc backstepping
fdcl-ftc/fault-tolerant-control pull request #38
Opened 2021-05-03 08:37 UTC by JinraeKim

Resolve #37.

원래는 #28 를 구현하고 있었으나, 구현상의 검토를 위해 active ftc backstepping controller 를 먼저 구현함 (참고로, active 버전은 모르는 LoE 를 FDI 모듈로 받아 쓴다는 가정을 하고 있음).

본 PR 의 검토 및 머지 이후 #28 작업을 시작할 예정.

## Summary
1. `ftc/agents/backstepping.py` 에 제어기 관련 클래스를 작성함.
2. `main.py` 를 수정하여 FDI + active FTC backstepping 제어기를 테스트해볼 수 있는 `exp2` 를 추가함.

### Results
<img width="634" alt="image" src="https://user-images.githubusercontent.com/43136096/116856501-3443c480-ac36-11eb-8d90-954f183c8cc9.png">

### Notes
시뮬레이터 틀인 `main.py` 를 구성한 @seong-hun 을 리뷰어로 추가함.

2021-05-03 12:03 UTC, seong-hun requested changes
`ftc/agents/passive_ftc.py.bak`는 커밋할 필요가 없어 보이는데 맞나요?

Python linting 기능을 지금 못쓰고 있다고 들었는데 티가 좀 나네요.. PEP8 체크도 다시 한 번 합시다.

2021-05-04 04:18 UTC, JinraeKim commented
> `ftc/agents/passive_ftc.py.bak`는 커밋할 필요가 없어 보이는데 맞나요?
> 
> Python linting 기능을 지금 못쓰고 있다고 들었는데 티가 좀 나네요.. PEP8 체크도 다시 한 번 합시다.

@seong-hun `pyright` 라는걸 쓰고 있는데 뭔가 linting 이 다른건지, 저는 안 나와서 ㅠㅠ
일단 형의 코멘트를 반영하겠습니다

2021-05-04 04:20 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +        return self.xd.state, self.vd.state, self.ad.state, self.ad_dot.state, self.ad_ddot.state, self.Td.state
Resolved in 7231e5c

2021-05-04 04:21 UTC, seong-hun commented
> > `ftc/agents/passive_ftc.py.bak`는 커밋할 필요가 없어 보이는데 맞나요?
> > Python linting 기능을 지금 못쓰고 있다고 들었는데 티가 좀 나네요.. PEP8 체크도 다시 한 번 합시다.
> 
> @seong-hun `pyright` 라는걸 쓰고 있는데 뭔가 linting 이 다른건지, 저는 안 나와서 ㅠㅠ
> 일단 형의 코멘트를 반영하겠습니다

pyright이 PEP8 체크해주는 프로그램이 맞나요? 안나올리가 없는데... ([예시](https://www.python.org/dev/peps/pep-0008/#blank-lines))

2021-05-04 04:22 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +        info = dict(t=t, xd=xd, vd=vd, ad=ad, ad_dot=ad_dot, ad_ddot=ad_ddot, Td=Td)
Resolved in c60397c

2021-05-04 04:23 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +        done = self.clock.time_over()
별다른 이유는 없었습니다 ㅠㅠ.. 제가 옛날 코드를 참고해서 짜서 그런듯

2021-05-04 04:23 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +        done = self.clock.time_over()
Resolved in 9ce84cc

2021-05-04 04:27 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +        Bp = np.vstack([np.zeros((3, 3)), (1/m)*np.eye(3)])
오.. 있는지 몰랐는데 유용하네요 땡큐!
Resolved in d6f25f7

2021-05-04 04:31 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +        P = scipy.linalg.solve_lyapunov(Ap.T, -self.Q)
Very good comment!
Resolved in b19c53e

2021-05-04 04:32 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +
@seong-hun 예전에는 reset 이 필요했던 것 같은데, 지금은 없어도 되나요? 잘 몰라서 ㅎ..

2021-05-04 04:33 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +        x = x.squeeze()
Resolved in 9f89eb0

2021-05-04 04:34 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +
Resolved in 79a2d43

2021-05-04 04:34 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +def T_u_inv(T):
Resolved in 79a2d43

2021-05-04 04:34 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +
Resolved in 79a2d43

2021-05-04 04:34 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +
Resolved in 79a2d43

2021-05-04 04:36 UTC, JinraeKim commented on main.py
> +        quat0 = angle2quat(*angle0)
Resolved in e6a3787

2021-05-04 04:36 UTC, JinraeKim commented
> > > `ftc/agents/passive_ftc.py.bak`는 커밋할 필요가 없어 보이는데 맞나요?
> > > Python linting 기능을 지금 못쓰고 있다고 들었는데 티가 좀 나네요.. PEP8 체크도 다시 한 번 합시다.
> > 
> > 
> > @seong-hun `pyright` 라는걸 쓰고 있는데 뭔가 linting 이 다른건지, 저는 안 나와서 ㅠㅠ
> > 일단 형의 코멘트를 반영하겠습니다
> 
> pyright이 PEP8 체크해주는 프로그램이 맞나요? 안나올리가 없는데... ([예시](https://www.python.org/dev/peps/pep-0008/#blank-lines))
> 뭐 PEP8을 안쓰거나 각자 linting을 하고 싶으면 제가 그렇게 따르도록 하죠 ㅎㅎ

일단 제가 pyright 에 블랭크가 꺼져있는지 등을 확인해보겠습니다~

2021-05-04 04:37 UTC, seong-hun commented
#40 에서 린터 관련 이슈를 하나 팠습니다.

2021-05-04 04:37 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +        omegad = np.vstack((u2[0][0], u2[1][0], 0))
Resolved in 47b85b3

2021-05-04 04:47 UTC, JinraeKim commented on ftc/agents/passive_ftc.py
> +
일단 없어도 잘 돌아가서 없앰.
Resolved in 8b0e889

2021-05-04 05:01 UTC, JinraeKim commented
@seong-hun Reflect your comments; plz check it out

2021-05-04 05:04 UTC, seong-hun commented
> `ftc/agents/passive_ftc.py.bak`는 커밋할 필요가 없어 보이는데 맞나요?

이 파일은 그냥 올리실 예정?

2021-05-04 06:30 UTC, JinraeKim commented
> > `ftc/agents/passive_ftc.py.bak`는 커밋할 필요가 없어 보이는데 맞나요?
> 
> 이 파일은 그냥 올리실 예정?

헐 뺄게요 ㅋㅋ

2021-05-04 06:33 UTC, JinraeKim commented
Note: `ftc/agents/passive_ftc.py.bak` 을 지우고, `main.py` 에서 `self.passive_ftc` 를 `self.controller` 로 변경함

2021-05-04 06:42 UTC, seong-hun approved these changes

2021-05-04 06:54 UTC, merged