Multicoptor test
fdcl-ftc/fault-tolerant-control pull request #41
Opened 2021-05-04 05:04 UTC by miaerosae

#31 
z 방향 tracking 및, z, yaw angle 제어만 가능합니다..
게인의 문제이길 빌어봅니다!

+ branch 이름에 오타가 있음을 확인

2021-05-04 05:12 UTC, seong-hun requested changes
`ftc/models/model_test.py`와 `ftc/models/model_test_fym.py`
위 두 파일은 여기다가 넣지 말고, `./test` 디렉터리를 루트(`fault-tolerant-control`)에 만들어서 거기다가 모아두는게 좋아 보입니다.

2021-05-04 05:12 UTC, seong-hun commented on ftc/agents/lqr_tracking.py
> +        return t, states, rotors, done
이거는 `ftc/models/multicopter.py`에 만들어 두었으니 모듈을 불러와서 씁시다.

2021-05-04 05:12 UTC, seong-hun commented on ftc/agents/lqr_tracking.py
> +    system.close()
```suggestion
    system.close()
    logger.close()
```

`logger.close()`를 해주어야 합니다. `system.logger`로 등록하고, `system.logger_callback`을 작성하지 않는 이상

2021-05-04 05:12 UTC, seong-hun commented on ftc/agents/lqr_tracking.py
> +    quat_pertb = np.array([angle2quat(yaw*d2r, pitch*d2r, roll*d2r)]).reshape((4, 1))
`np.deg2rad` 메소드가 있습니다~

예를 들어 다음과 같이 작성 가능:
```python
quat_pertb = np.vstack(angle2quat(np.deg2rad(yaw, pitch, roll)))
```

2021-05-04 05:20 UTC, miaerosae commented on ftc/agents/lqr_tracking.py
> +        return t, states, rotors, done
state variable을 바꾸었을 뿐만 아니라 중간에 선형화해서 lqr을 사용하는 코드가 추가적으로 들어가 있어 모듈을 불러오는게 어려울것 같다 생각했습니다ㅜ

2021-05-04 05:39 UTC, seong-hun commented on ftc/agents/lqr_tracking.py
> +        return t, states, rotors, done
음.. 지금 제어기는 선형이지만, Multirotor 클래스는 비선형이기 때문에 이거를 선형화해서 새로운 클래스를 만든거라고 이해가 되는데 맞나요? 그러면, 선형 제어기 + 선형 모델이란건데.. 음 그럼 이건 스크립트인가? 스크립트면 `./test` 디렉터리에 넣어 주새요~

참고로 연구를 할 때 보통은 선형제어기 + 비선형모델로 시뮬레이션을 수행합니다. (실제 상황과 유사한 상황에서 제어기 성능을 보기 위함)

그리고, 지금 이 코드의 의도가 Agent 모듈을 만드는 것이라면 Multicopter 모듈과 어느정도 독립적이게 코드를 짜야하겠습니다.
Multicopter를 염두에 두기는 하지만 initial condition이나 무게, 회전관성 등이 바뀌어도 호환이 되게끔.. 조금 어려울 순 있겠는데, 코드를 일단 보고 같이(@JinraeKim  @hnlee77 ) 수정해 나갑시다.

2021-05-04 05:44 UTC, miaerosae commented on ftc/agents/lqr_tracking.py
> +        return t, states, rotors, done
선형제어기 + 비선형 모델입니다!
비선형 모델 선형화해서 lqr로 input만 구하고 비선형 모델에 넣었습니다

스크립트..? 그냥 코드는 맞습니다! ./test 생성해서 거기로 옮겨서 푸쉬했는데 풀리퀘가 여기에 반영되는것인지 따로 해야 하는것인지 모르겠어요.. 

음 ic, 무게, 회전관성 등이 Multicopter 모듈과 같이 처음에 설정이 되어 있어서 바뀌어도 돌아갈 것 같기는 합니다..!

2021-05-04 05:45 UTC, seong-hun commented on ftc/agents/lqr_tracking.py
> +    quat_pertb = np.array([angle2quat(yaw*d2r, pitch*d2r, roll*d2r)]).reshape((4, 1))
죄송.. 다음이 맞겠다.
```python
angle2quat(*np.deg2rad([yaw, pitch, roll]))
```

2021-05-04 05:47 UTC, seong-hun commented
우선, 코드는 잘 돌아가네요~

<img width="752" alt="image" src="https://user-images.githubusercontent.com/9782545/116964934-a4f6e980-ace7-11eb-8dde-4f13cf0127f2.png">

<img width="752" alt="image" src="https://user-images.githubusercontent.com/9782545/116964931-a0323580-ace7-11eb-8f40-018f05b107e0.png">

2021-05-04 05:52 UTC, miaerosae commented on ftc/agents/lqr_tracking.py
> +    quat_pertb = np.array([angle2quat(yaw*d2r, pitch*d2r, roll*d2r)]).reshape((4, 1))
둘 다 
ValueError: invalid number of arguments
의 에러가 뜨면서 돌아가지 않습니다..! 

앗 아래껀 어떻게 돌아간거지

2021-05-04 06:01 UTC, miaerosae commented on ftc/agents/lqr_tracking.py
> +    quat_pertb = np.array([angle2quat(yaw*d2r, pitch*d2r, roll*d2r)]).reshape((4, 1))
해결했습니당!

2021-05-04 06:29 UTC, JinraeKim commented
@miaerosae [Github docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) 에 명시되어있듯이, 깃헙이 몇 가지 단어를 인식해서 이슈-풀리퀘간 링크를 걸 수 있습니다.

매뉴얼하게 하는 방법은, 풀리퀘 등에서 직접 linked issues 를 추가하는 겁니다 (아래 참고).
![image](https://user-images.githubusercontent.com/43136096/116967523-6d8b3b80-aced-11eb-97d8-977c5d1fa7e9.png)

이 PR 에 대응되는 이슈를 잘 링크해보세요~

2021-05-04 06:39 UTC, hnlee77 commented on ftc/agents/lqr_tracking.py
> +        return t, states, rotors, done
독립적으로 agent 모듈을 만들어 나가도록 제가 도와줘볼게요~

2021-05-04 06:55 UTC, JinraeKim commented
@miaerosae PR 이름을 바꾸는게 좋을듯~

2021-05-04 07:51 UTC, seong-hun commented
PR #43 올렸습니다~
[비교](https://github.com/fdcl-ftc/fault-tolerant-control/pull/43/files)를 보면서 스크립트를 작성할 때, Multirotor 클래스를 어떻게 쓰는지 등을 보면 좋을 것 같습니다.

2021-05-06 02:43 UTC, miaerosae commented
#31 

env와 obs를 받아 input을 계산하는 LQR agent를 만들었습니다.
ic, J, m을 다 받고 싶어서 env를 받아보려 했는데 잘 한 짓인가에 대해서는 의문이 듭니다...

+ git push를 하면 자동으로 여기의 풀리퀘에 올라가는데, 새로운 풀리퀘를 만드려면 새로운 브랜치를 파야 하는 것일까요??

2021-05-06 03:49 UTC, seong-hun commented
> ic, J, m을 다 받고 싶어서 env를 받아보려 했는데 잘 한 짓인가에 대해서는 의문이 듭니다...

저는 모듈화를 할 때에는 env를 받지 않는데, 그 이유는 env 내에서 변수 정의가 controller 모듈에서 사용하는 변수명과 동일하게 정의되어 있지 않을 경우가 있기 때문입니다. Controller를 초기화(`__init__`) 할 때, 필요한 인자를 명시하면 다양한 env와 함께 쓰기에 편리할 것 같습니다.
다만, 개발중인 모듈의 경우에는 편의상 지금처럼 해 놓고, 나중에 어느정도 완성도 있게 짜여졌을때 수정하는 것이 편할 수도 있겠네요.

> * git push를 하면 자동으로 여기의 풀리퀘에 올라가는데, 새로운 풀리퀘를 만드려면 새로운 브랜치를 파야 하는 것일까요??

일단은 그렇게 생각이 되는데.. 아마 링크를 끊을 수도 있겠지만, 새로운 주제로 풀리퀘를 만들 것이 아니라면 그렇게 할 이유가 있나요?
새로운 주제로 풀리퀘를 할 거면 브랜치를 새로 파는게 자연스러워 보입니다.

2021-05-06 04:13 UTC, miaerosae commented
- 넵 그러면 인자 명에 대해서는 나중에 수정하겠습니다
- 감사합니당!

2021-05-06 04:19 UTC, seong-hun requested changes
`ftc/agents/LQR_copter.py` -> `ftc/agents/lqr.py` 로 제안해봅니다.

불러올 때, `import ftc.agents.lqr`로 통일감있게 불러올 수 있게..
참고로 아마? PEP8 권장은 모듈 이름은 소문자로, 클래스 이름은 의미상 첫 글자만 대문자로 입니다.
(ex. `lqr.py`, `class LQRController`) (사실 `LQR`도 `Lqr`이 맞겠으나 이 정도는 우리 분야 특성상 이게 더 자연스러울듯)

`ftc/agents/lqr_tracking.py` 이 파일은 `git rm` 명령어로 지워야 할 듯 합니다. (지우는게 맞다면)

`ftc/models/model_test.py`, `ftc/models/model_test_fym.py` 이 파일들은 `test` 폴더로 옮겨야 하지 않을까요? (`git mv` 명령어 사용 가능)

`test/lqr_tracking.py` 파일에서 이제는 `Mixer`와 `Multicopter` 클래스를 지워도 되지 않나요?

2021-05-06 04:19 UTC, seong-hun commented on ftc/models/multicopter.py
> +
이것은.. 뭔가 따로 메소드로 만들던지 해야할 것 같이 생겼는데요?

2021-05-06 04:19 UTC, seong-hun commented on ftc/models/multicopter.py
> +        self.n_rotor = B.shape[1]
이건 `Multicopter` 클래스 안에 넣는게 어떨까요?

2021-05-07 03:32 UTC, miaerosae commented
말씀해주신 수정사항 반영해서 
'lqr agent test -fin' 이후 3개의 커밋에 올렸습니다. 그 앞에껀 수정사항 반영 전이라 무시하셔도 됩니다!

-  `self.ic` 의 경우 제가 저걸 왜 쓴지 모르겠어요.. 지금은 없앴습니다
- `self.n_rotors` 의 경우 `Multicopter` 클래스 내부로 이동시켰습니다


아래는 reference z = -50에서 조금의 perturbation(z = z+3, yaw = yaw + 10deg)을 주고 돌려본 코드입니다.
input이 잘 들어간거 같긴 합니다!

![Figure_1](https://user-images.githubusercontent.com/80808711/117393917-1a54fb00-af30-11eb-87e5-887f63f2854e.jpg)
![Figure_2](https://user-images.githubusercontent.com/80808711/117393935-23de6300-af30-11eb-8cc5-41c739cf4769.jpg)

2021-05-07 06:23 UTC, miaerosae commented
커밋하는 과정에서 무언가가 꼬여서 이상한 파일들이 올라갔는데, 
"lqr agent test -fin" 부분만 보시면 될 것 같습니당

2021-05-11 09:12 UTC, seong-hun commented
우선 rebase를 해 주세요~ @hnlee77

2021-05-11 09:23 UTC, hnlee77 commented
이것은 rebase를 도와주라는 의미로 태그를 단 것이죠??

2021-05-11 09:24 UTC, seong-hun commented
> 이것은 rebase를 도와주라는 의미로 태그를 단 것이죠??

넵

2021-05-14 03:39 UTC, miaerosae commented
PR (#63 ) 에서 해결

2021-05-14 04:15 UTC, closed without merging