Comparison Scenario
fdcl-ftc/fault-tolerant-control pull request #66
Opened 2021-05-21 13:22 UTC by hnlee77

Add main file for comparison scenario A1-A3

## LQR controller for scenario A1

2021-05-24 04:18 UTC, JinraeKim commented
@hnlee77 결과 요약 보면 호버링이 제대로 수행되고 있지 않다고 되어있는데, 작업중인 PR 인건가요?
만약 그렇다면 draft 로 돌려주시면 좋을듯~

저는 일단 direct backstepping controller 구현을 마무리한 뒤 시나리오 구현을 하겠습니다.

2021-05-24 04:20 UTC, JinraeKim commented on ftc/agents/CA.py
> +
mixer 클래스가 동일한 역할을 하는 것 같은데, 추가로 CA 클래스가 있는 이유가 있나요?

2021-05-24 04:56 UTC, hnlee77 commented
> @hnlee77 결과 요약 보면 호버링이 제대로 수행되고 있지 않다고 되어있는데, 작업중인 PR 인건가요?
> 만약 그렇다면 draft 로 돌려주시면 좋을듯~

시나리오 구현을 완료한 결과이고 호버링이 정확히 수행되지 않았습니다. 로터 한개 Failure 고장에 대해서 강건하지 않은 것 같아 보입니다.

2021-05-24 04:58 UTC, hnlee77 commented on ftc/agents/CA.py
> +
mixer와 동일한 역할을 하는 것은 아니고, 정확히는 CA를 수행하는데 고장난 로터를 제외한 나머지 로터들에 조종력을 할당하는 역할을 합니다.

2021-05-24 05:06 UTC, JinraeKim reviewed
코멘트 추가했습니다 ㅎㅎ

2021-05-24 05:06 UTC, JinraeKim commented on ftc/agents/CA.py
> +            self.B[:, 4:] = np.zeros((4, 2))
multicopter 모델을 받아와서 grouping indexing 을 정하는게 어떨까요?
예를 들어, quadcopter 면 이러한 grouping 이 안되도록 사전에 막아야할 것이고, hexacopter 중에서도 0-1, 2-3, 4-5 끼리 묶이지 않은 모델이 있을수도 있으니... (실제로 `hexa-falconi` 는 저렇게 묶이진 않습니다)

확장성을 위해서는 multicopter 모델을 받아서
1) 해당 모델이 hexacopter 가 아니면: 오류
2) hexacopter 이면: 각 헥사콥터의 인덱싱에 대한 프로퍼티를 불러와서 grouping 수행

이런 식으로요!

2021-05-24 05:06 UTC, JinraeKim commented on ftc/agents/CA.py
> +
지금은 하나의 인덱스만 가능하게 되어있는데, 여러 개의 로터가 고장났을 때에도 적용할 수 있게 `fault_indicies` 를 받아서 해당 열을 다 날리는건 어떨까요?

2021-05-24 05:24 UTC, JinraeKim commented
@hnlee77 님 그래프 ylim 맞춰주세요 ㅎㅎ

2021-05-24 05:24 UTC, JinraeKim commented on test/failure_scenario.py
> +    plt.show()
ylim 맞춰주세요 ㅎㅎ

2021-05-24 06:31 UTC, hnlee77 commented on ftc/agents/CA.py
> +            self.B[:, 4:] = np.zeros((4, 2))
그렇군요 grouping indexing을 정하는게 필요하겠네요... 코멘트 감사해요! 이것을 새로 이슈로 파는게 낫겠어요.

2021-05-24 06:32 UTC, hnlee77 commented on test/failure_scenario.py
> +    plt.show()
넵 알겠습니다!

2021-05-24 06:34 UTC, seong-hun commented on ftc/agents/CA.py
> +
> 지금은 하나의 인덱스만 가능하게 되어있는데, 여러 개의 로터가 고장났을 때에도 적용할 수 있게 `fault_indicies` 를 받아서 해당 열을 다 날리는건 어떨까요?

저렇게 작성해도 진래가 원하는 것처럼 작동합니다.

2021-05-25 01:08 UTC, JinraeKim commented
> > @hnlee77 결과 요약 보면 호버링이 제대로 수행되고 있지 않다고 되어있는데, 작업중인 PR 인건가요?
> > 만약 그렇다면 draft 로 돌려주시면 좋을듯~
> 
> 시나리오 구현을 완료한 결과이고 호버링이 정확히 수행되지 않았습니다. 로터 한개 Failure 고장에 대해서 강건하지 않은 것 같아 보입니다.

LQR 의 경우, 로터 한개 고장 이후 5개로 조종력을 배분하면 호버링이 되야할 것 같습니다.

2021-05-26 13:14 UTC, hnlee77 commented
> > > > @hnlee77 결과 요약 보면 호버링이 제대로 수행되고 있지 않다고 되어있는데, 작업중인 PR 인건가요?
> > > > 만약 그렇다면 draft 로 돌려주시면 좋을듯~
> > > 
> > > 
> > > 시나리오 구현을 완료한 결과이고 호버링이 정확히 수행되지 않았습니다. 로터 한개 Failure 고장에 대해서 강건하지 않은 것 같아 보입니다.
> > 
> > 
> > LQR 의 경우, 로터 한개 고장 이후 5개로 조종력을 배분하면 호버링이 되야할 것 같습니다.
> 
> 네 저도 그렇게 생각이 되는데요... 문제를 파악해보도록 하겠습니다.

로터 한개 고장에 대해서 호버링이 되어야 할 것 같다고 생각이 되는데 점점 발산하네요.. 속도가 잡히지 않는 것 같은데 게인을 조절해도 마찬가지입니다. 다들 한번 살펴봐주쎄요... @seong-hun @JinraeKim

2021-05-26 13:25 UTC, JinraeKim commented
> > > > > @hnlee77 결과 요약 보면 호버링이 제대로 수행되고 있지 않다고 되어있는데, 작업중인 PR 인건가요?
> > > > > 만약 그렇다면 draft 로 돌려주시면 좋을듯~
> > > > 
> > > > 
> > > > 시나리오 구현을 완료한 결과이고 호버링이 정확히 수행되지 않았습니다. 로터 한개 Failure 고장에 대해서 강건하지 않은 것 같아 보입니다.
> > > 
> > > 
> > > LQR 의 경우, 로터 한개 고장 이후 5개로 조종력을 배분하면 호버링이 되야할 것 같습니다.
> > 
> > 네 저도 그렇게 생각이 되는데요... 문제를 파악해보도록 하겠습니다.
> 
> ~~로터 한개 고장에 대해서 호버링이 되어야 할 것 같다고 생각이 되는데 점점 발산하네요.. 속도가 잡히지 않는 것 같은데 게인을 조절해도 마찬가지입니다. 다들 한번 살펴봐주쎄요...~~ @seong-hun @JinraeKim 
> 잘되네요.

어떻게 해결된건지 공유 부탁드림

2021-05-26 14:12 UTC, hnlee77 commented
> > > > > > @hnlee77 결과 요약 보면 호버링이 제대로 수행되고 있지 않다고 되어있는데, 작업중인 PR 인건가요?
> > > > > > 만약 그렇다면 draft 로 돌려주시면 좋을듯~
> > > > > 
> > > > > 
> > > > > 시나리오 구현을 완료한 결과이고 호버링이 정확히 수행되지 않았습니다. 로터 한개 Failure 고장에 대해서 강건하지 않은 것 같아 보입니다.
> > > > 
> > > > 
> > > > LQR 의 경우, 로터 한개 고장 이후 5개로 조종력을 배분하면 호버링이 되야할 것 같습니다.
> > > 
> > > 
> > > 네 저도 그렇게 생각이 되는데요... 문제를 파악해보도록 하겠습니다.
> > 
> > 
> > ~로터 한개 고장에 대해서 호버링이 되어야 할 것 같다고 생각이 되는데 점점 발산하네요.. 속도가 잡히지 않는 것 같은데 게인을 조절해도 마찬가지입니다. 다들 한번 살펴봐주쎄요...~ @seong-hun @JinraeKim
> > 잘되네요.
> 
> 어떻게 해결된건지 공유 부탁드림

뭔가 다른 문제가 있어보입니다. 
```rotors = np.clip(rotors, 0, self.plant.rotor_max)```
구동기 제한조건을 지우면 제어가 잘 되는데 필요한 제어입력이 구동기 제한 조건에 걸리지 않는 것으로 보여지거든요...

![image](https://user-images.githubusercontent.com/32696021/119674918-911e4d80-be77-11eb-8df0-d0e16e375d6c.png)
![image](https://user-images.githubusercontent.com/32696021/119675008-a0050000-be77-11eb-81c2-e78e50f419d8.png)

2021-05-26 14:30 UTC, hnlee77 commented
음.. #68 에서 언급된 상황은 대칭이 아닌 로터 2개의 고장에 대해서 제어가 되지 않는 문제라서 로터 방향이 다르기 때문에 하한값이 그런 상황을 야기시킬 수 있을 것 같아요. 그런데 여기서는 1개의 고장에 대해서이고, 로터 입력 그래프를 보면 거의 0과 가까운 값이 나오기는 해요. 그래서 수치적인 문제인 것일까 하는 의문...

2021-05-26 15:08 UTC, JinraeKim commented
> 음.. #68 에서 언급된 상황은 대칭이 아닌 로터 2개의 고장에 대해서 제어가 되지 않는 문제라서 로터 방향이 다르기 때문에 하한값이 그런 상황을 야기시킬 수 있을 것 같아요. 그런데 여기서는 1개의 고장에 대해서이고, 로터 입력 그래프를 보면 거의 0과 가까운 값이 나오기는 해요. 그래서 수치적인 문제인 것일까 하는 의문...

#69 의 결과를 보면, 수치적 문제라고 보기 힘들어보입니다 (로터 입력이 0에 가깝게 나옴; 사실 이게 왜 수치적 문제로 결론이 나는지 잘 모르겠음. 부가 설명 가능할까요?).

개인적으로는, #68 과 여기서 LQR 제어기가 공통적으로 문제를 보이는것으로 보아 제어기 문제일 가능성이 높아보이고...
#69 의 제어기는 위치 제어만 목표인데 반해, LQR 제어기는 모든 state를 잡으려고 하기 때문에 발생하는 문제일수도 있을 것 같습니다 (예를 들어 위치를 잡기 위해서 yaw 방향 회전이 불가피한 고장상황이라고 하면, #69의 제어기는 yaw 를 포기하겠지만 LQR 은 모든 상태변수가 0에 있도록 작성되어있더라고요. 그럼 LQR이 위치 오차를 포기할수도 있지 않을까요?).

2021-05-27 03:23 UTC, hnlee77 commented
> > 음.. #68 에서 언급된 상황은 대칭이 아닌 로터 2개의 고장에 대해서 제어가 되지 않는 문제라서 로터 방향이 다르기 때문에 하한값이 그런 상황을 야기시킬 수 있을 것 같아요. 그런데 여기서는 1개의 고장에 대해서이고, 로터 입력 그래프를 보면 거의 0과 가까운 값이 나오기는 해요. 그래서 수치적인 문제인 것일까 하는 의문...
> 
> #69 의 결과를 보면, 수치적 문제라고 보기 힘들어보입니다 (로터 입력이 0에 가깝게 나옴; 사실 이게 왜 수치적 문제로 결론이 나는지 잘 모르겠음. 부가 설명 가능할까요?).
> 
이부분은 커맨드 자체가 0와 비슷한 (-1e-13 정도) 값을 주는 것이 문제라고 생각했는데 애초에 커맨드를 잘못 그리고 있었네요. 즉, 수치적 문제는 아니네요 ㅎㅎ 미안합니다. 

> 개인적으로는, #68 과 여기서 LQR 제어기가 공통적으로 문제를 보이는것으로 보아 제어기 문제일 가능성이 높아보이고...
> #69 의 제어기는 위치 제어만 목표인데 반해, LQR 제어기는 모든 state를 잡으려고 하기 때문에 발생하는 문제일수도 있을 것 같습니다 (예를 들어 위치를 잡기 위해서 yaw 방향 회전이 불가피한 고장상황이라고 하면, #69의 제어기는 yaw 를 포기하겠지만 LQR 은 모든 상태변수가 0에 있도록 작성되어있더라고요. 그럼 LQR이 위치 오차를 포기할수도 있지 않을까요?).
> 위의 예상이 맞다면, LQR 제어기를 특정 state 에 특화해서 작성해야할듯하네요 (예를 들어 위치 제어).

제 생각에도 말씀하신 내용의 문제일 가능성이 가장 커보이네요.

2021-05-27 04:17 UTC, hnlee77 commented
![image](https://user-images.githubusercontent.com/32696021/119765235-d3827180-beed-11eb-9a1d-c04a1865ca00.png)
![image](https://user-images.githubusercontent.com/32696021/119765254-e1d08d80-beed-11eb-8d22-b747e677b646.png)

2021-05-27 04:53 UTC, hnlee77 commented
@JinraeKim 가 제어기 교체를 제안함.
이는 머지 후에 진행하겠습니다.

2021-05-27 04:56 UTC, JinraeKim commented
> @JinraeKim 가 제어기 교체를 제안함.
> 이는 머지 후에 진행하겠습니다.

뉘앙스를 말하자면:
만일 위 현상이 lqr의 본질적 한계라면, 이외에도 다른 제어기가 추가되었으면 좋겠습니다.
원래 진행중이던 DSC는 어떻게 되고 있나요? @seong-hun

2021-05-27 05:06 UTC, hnlee77 commented
네 추가적으로 다양한 고장허용 제어기를 추가해 나가도록 합시다.

2021-05-28 06:43 UTC, hnlee77 commented
@seong-hun 리뷰후에 머지할게요.

2021-05-28 12:50 UTC, JinraeKim approved these changes
제 리뷰는 직접 만나서 수정했던 ceb55b5 및 앞의 리뷰로 대체하겠습니다 ㅎ

2021-05-28 12:54 UTC, JinraeKim commented on ftc/agents/lqr.py
> +        return np.vstack((y[0:6], np.vstack(quat2angle(y[6:10])[::-1]), y[10:]))
이건 들어오는 상태변수의 조합이 달라질수도 있는거니, `transform(pos, vel, quat, omega)` 정도로 명시해주는게 좋을 것 같아요.

2021-05-28 12:54 UTC, JinraeKim commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
개인적으로는 전부터 힘이 아닌 모멘트를 포함해서 `forces` 로 칭하는게 혼란을 야기한다고 생각했는데, 네이밍을 바꿔보는건 어떨까요?

2021-05-28 12:55 UTC, JinraeKim commented
> @JinraeKim 가 제어기 교체를 제안함.
> 이는 머지 후에 진행하겠습니다.

근데 개인적으로는, 제대로 돌아가는 제어기가 먼저 있어야 시나리오를 검증하는게 유의미할 것 같긴 합니다.

2021-05-28 14:37 UTC, hnlee77 commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
음... 혹시 추천하는 네이밍이 있나요? 저도 그렇긴 한데 forcemoment라고 하기에는 또 길어지고..

2021-05-28 14:45 UTC, JinraeKim commented
> > > @JinraeKim 가 제어기 교체를 제안함.
> > > 이는 머지 후에 진행하겠습니다.
> > 
> > 
> > 근데 개인적으로는, 제대로 돌아가는 제어기가 먼저 있어야 시나리오를 검증하는게 유의미할 것 같긴 합니다.
> 
> 제어기 자체는 잘 돌아가는 것이지만 기법적인 한계가 있는 것으로 생각해도 될까요? 그리고 시나리오 1과 2에 대해서 같은 제어기법으로 비교를 해보는 것이 의미가 있다고 생각을 하는데요. 혹시 이와 관련된 내용으로 보고서에 LQR제어기의 한계점, 그리고 시나리오 2와 같이 미리 설계된 로터를 이용한 제어기 설계(같은 제어기법이지만)와의 차이로써 결과를 작성한 후에 다른 비선형 제어기법 (Feedback Linearization과 같은 기법) 으로 교체 후 그것을 비교한 것도 포함하여 추후 미팅때에 작성하는 것은 어떻게 생각해요?

오호... 적절할 것 같네요 ㅎㅎ

2021-05-28 14:46 UTC, hnlee77 commented on ftc/agents/lqr.py
> +        return np.vstack((y[0:6], np.vstack(quat2angle(y[6:10])[::-1]), y[10:]))
네 이건 그렇게 수정할게요.

2021-05-28 14:46 UTC, JinraeKim commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
그냥 `get_force_and_moment` 도 괜찮을 것 같고...
약간 심볼릭하게는 `get_FM` 으로 쓸수도 있을 것 같고...?

2021-05-28 14:47 UTC, hnlee77 commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
get_FM 어때요?

2021-05-28 14:52 UTC, JinraeKim commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
전 좋다고 봅니다 ㅎ

2021-05-31 03:19 UTC, seong-hun requested changes

2021-05-31 03:19 UTC, seong-hun commented on ftc/agents/lqr.py
> +                      [0, 0, 0, 0, 0, 0, self.g, 0, 0, 0, 0, 0],
이런것들 `self` 빼도 되지 않나요? 왜 바꾼것인지..

2021-05-31 03:19 UTC, seong-hun commented on ftc/agents/lqr.py
> +        return np.vstack((y[0:6], np.vstack(quat2angle(y[6:10])[::-1]), y[10:]))
선형제어기 짤 때, 그냥 `y`로 두는게 편하긴 한데..

2021-05-31 03:19 UTC, seong-hun commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
모멘트도 generalized force 인데... ㅠㅋㅋ

2021-05-31 03:19 UTC, seong-hun commented on ftc/agents/lqr.py
> +        forces = -self.K.dot(x - x_ref) + self.trim_forces
저도 이렇게 짜긴 했지만, 한가지 의문은 왜 feedforward 입력을 쓰지 않고, 트림점을 `x_ref`로 바꿔버리는가 하는 것인데... @JinraeKim @miaerosae  어떻게들 생각하시는지요?

2021-05-31 03:19 UTC, seong-hun commented on test/scenario_a_1.py
> +    plt.plot(data["t"], -data["x"]["pos"][:, 2, 0], "k-.", label="z")  # z
이렇게 할거면 `z`가 아니라 고도를 의미하도록 레이블을 `h` 이런걸로 바꿔야 하지 않을까요?

2021-05-31 03:19 UTC, seong-hun commented on test/scenario_a_1.py
> +        fault_index = self.fdi.get_index(What)
이 부분 조금 고민했었는데, 교수님 요구사항에서는 0.2초의 딜레이가 있어야 합니다. 지금은 LPF로 딜레이 비스무리하게 두고 있는데, [제 시나리오](https://github.com/fdcl-ftc/fault-tolerant-control/blob/56cadb7b981b40ae1cf269069328c76407d4a777/ftc/agents/fdi.py#L20)를 참고해서 일정 값 이하로 내려가면 failure로 판단하도록 설정하는게 어떨까요?

2021-05-31 03:38 UTC, JinraeKim commented on test/scenario_a_1.py
> +    plt.plot(data["t"], -data["x"]["pos"][:, 2, 0], "k-.", label="z")  # z
오 이건 숨은 함정이네 ㄷㄷ
NED 아니면 ENU 로 그리는걸 기본으로 하는게 좋겠습니다.

2021-05-31 03:41 UTC, JinraeKim commented on test/scenario_a_1.py
> +        fault_index = self.fdi.get_index(What)
교수님 요구사항이 딜레이 0.2초면 딜레이 형태로 주는게 나을 것 같은데, 그럼 LPF 나 아니면 아예 shift 된 형태로 FDI 가 작동하는게 어울리지 않을까 싶습니다.
Threshold 를 잡고 그 이하에서 failure 로 판단하는게 딜레이를 주는 것과 직접적인 연관이 있는지 잘 모르겠는데... 좀 더 설명 부탁드리겠습니다

2021-05-31 03:44 UTC, JinraeKim commented on ftc/agents/lqr.py
> +        forces = -self.K.dot(x - x_ref) + self.trim_forces
만일 `ref` 가 time-varying 하다면 일단 `self.trim_forces` 도 업데이트가 되야할 것으로 보여서 수정이 필요해보입니다.

@seong-hun  이 말한 `feedforward` vs 트림 변경은 정확히 의미를 이해 못했는데, pseudo code가 있으면 이해가 더 쉬울 것 같습니다.

2021-05-31 03:45 UTC, JinraeKim commented on ftc/agents/lqr.py
> +        return np.vstack((y[0:6], np.vstack(quat2angle(y[6:10])[::-1]), y[10:]))
그냥 `y` 로 둔다면, `y` 가 어떻게 구성되어있는지 docstring 을 명시하고 인자를 받은 직후 `y`의 길이 체크를 수행하는게 좋겠습니다.

2021-05-31 03:47 UTC, JinraeKim commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
그럼 generalised_forces 나 gen forces 등으로 써도 괜찮겠네요.

2021-05-31 04:08 UTC, hnlee77 commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
아 그렇군요?! 그러면 ```get_generalised_forces``` 어때요?

2021-05-31 04:08 UTC, hnlee77 commented on ftc/agents/lqr.py
> +                      [0, 0, 0, 0, 0, 0, self.g, 0, 0, 0, 0, 0],
그렇군요.. 뺀거랑 안뺀거랑 뭔가 차이가 있나요?

2021-05-31 04:09 UTC, hnlee77 commented on ftc/agents/lqr.py
> +        return np.vstack((y[0:6], np.vstack(quat2angle(y[6:10])[::-1]), y[10:]))
네 그러면 docstring을 명시하는 것이 좋겠어요. 길이 체크는 총 13개의 인자가 들어오는지를 체크하라는 말이죠?

2021-05-31 04:10 UTC, seong-hun commented on test/scenario_a_1.py
> +        fault_index = self.fdi.get_index(What)
딜레이 형태로 주는게 가장 베스트이긴 한데요, 그래도 지금 구현되어 있는 LPF로도 비슷하게 흉내낼 수 있습니다.
(사실 LPF 형태로 유사 딜레이를 주는게 실제 FDI를 모사하기 더 적절한 것 같기도 하고...)

방법은 심플한데요, fault가 발생하면 FDI의 integrator는 1에서 서서히 0으로 갑니다. 이때, 시상수를 늘리면 더 천천히 내려가고 하겠죠. 그러면 예를 들어서 0.5 이하로 내려가는 순간이 대략 0.2초 정도 걸리게 세팅을 하면 됩니다.
샘플 코드는 지금 코드..

2021-05-31 04:10 UTC, hnlee77 commented on test/scenario_a_1.py
> +    plt.plot(data["t"], -data["x"]["pos"][:, 2, 0], "k-.", label="z")  # z
아하 그렇겠네요. 이것은 원래 D 방향대로 수정해 놓을게요.

2021-05-31 04:12 UTC, seong-hun commented on ftc/agents/lqr.py
> +        forces = -self.K.dot(x - x_ref) + self.trim_forces
샘플코드:
```python
forces = trim_forces - self.K_fb @ (x - xtrim) + self.K_ff @ x_ref
```

2021-05-31 04:13 UTC, seong-hun commented on ftc/agents/lqr.py
> +        forces = -self.K.dot(x - x_ref) + self.trim_forces
@miaerosae 가 지금 배우고 있지 않을까?ㅋㅋ

2021-05-31 04:13 UTC, seong-hun commented on ftc/agents/lqr.py
> +                      [0, 0, 0, 0, 0, 0, self.g, 0, 0, 0, 0, 0],
없어서 하는 얘깁니다 ㅋㅋ

2021-05-31 04:15 UTC, seong-hun commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
아..아뇨 그냥 해본소리였습니다 ㅠ 진래 표기법 추천

2021-05-31 04:28 UTC, hnlee77 commented on test/scenario_a_1.py
> +        fault_index = self.fdi.get_index(What)
그렇군요. 이해했어요. 이부분도 참고해서 설정할게요.

2021-05-31 04:44 UTC, hnlee77 commented on ftc/agents/lqr.py
> +                      [0, 0, 0, 0, 0, 0, self.g, 0, 0, 0, 0, 0],
넵 알겠습니다. 수정해놓을게요.

2021-05-31 04:45 UTC, hnlee77 commented on ftc/agents/lqr.py
> +    def get_forces(self, obs, ref):
그러면 간단하게 ```get_FM```으로 갑시다~

2021-05-31 04:58 UTC, miaerosae commented on ftc/agents/lqr.py
> +        forces = -self.K.dot(x - x_ref) + self.trim_forces
ㅋㅋㅋㅋ... 수업시간에 잠깐 나오기는 했습니다만 그렇게 자세하게 다루지는 않았습니당.. 보통 tracking 시 feedforward를 자주 사용하나요? 제가 본 것들에서는 사용된적이 없어서 생각해보지 않았습니다

2021-05-31 05:21 UTC, seong-hun commented on ftc/agents/lqr.py
> +        forces = -self.K.dot(x - x_ref) + self.trim_forces
좋은 기법 중 하나죠 ㅎㅎ FF 관련해서 배운 내용 슬랙이라던지 디스커션에 공유해주시면 감사드리겠슴다~~

2021-05-31 05:32 UTC, miaerosae commented on ftc/agents/lqr.py
> +        forces = -self.K.dot(x - x_ref) + self.trim_forces
앗 찾아보니 이번학기에는 배우지 않았네요.. 학부때 이런게 있다 정도 하고 넘어간것 같습니다

2021-06-02 06:01 UTC, hnlee77 commented
resolved #71
- @seong-hun 의 FDI 모듈 및 파라미터를 참고하여 수정

### 다른 수정사항
- ```get_force``` 메소드 이름 변경 -> ```get_FM```
- 그림 통일 :  #68 과 통일하도록 수정
- Reference 수정 : #68, #69 와 동일한 시나리오가 되도록 ```ref``` 수정
- 그림에서 ```z``` 수정 : 고도가 아닌 ```NED```좌표계에 따른 값을 표시하도록 수정
- docstring 명시 및 길이 체크 : 다음 [코멘트](https://github.com/fdcl-ftc/fault-tolerant-control/pull/66#discussion_r642192250) 참고

2021-06-02 16:36 UTC, hnlee77 commented on ftc/agents/lqr.py
> +        forces = -self.K.dot(x - x_ref) + self.trim_forces
일단 현재는 constant reference를 고려하고 있어서 미애가 짠 LQR제어기로도 괜찮을 것 같아서 사용했습니다. 
여기서 @JinraeKim 가 말한 time-varying하다면 ```self.trim_forces```가 업데이트 되어야 할 것 같다는 것을 이해를 못했어요...
또한 Time-varying reference를 따라가기 위해서는 LQI같은 방식을 써서 ```feedforward```입력을 함께 고려하는 것이 필요할 것 같아요.

2021-06-09 06:25 UTC, seong-hun approved these changes

2021-06-09 07:01 UTC, merged