Add fl controller
fdcl-ftc/fault-tolerant-control pull request #79
Opened 2021-06-09 04:49 UTC by hnlee77

Position tracking 을 위한 feedback linearization 제어기를 추가.
정상인 상태에서 위치제어는 잘 수행이 되지만 고장이 발생하는 경우 제어가 되지 않음.
- 제어기가 매우 민감한 것으로 생각됨.

2021-06-09 05:23 UTC, JinraeKim commented
> 정상인 상태에서 위치제어는 잘 수행이 되지만 고장이 발생하는 경우 제어가 되지 않음.
> 
> * 제어기가 매우 민감한 것으로 생각됨.

이런 결론에 대한 근거를 제시해주시면 좋겠습니다.
파라미터별 시뮬레이터 결과 같은걸 첨부한다던지...

2021-06-12 08:04 UTC, hnlee77 commented
위치 그래프를 붙여넣은 줄 알았는데 안올라갔네요..ㅎㅎ 글을 다시 정리해서 업데이트 했습니다.

2021-06-16 09:06 UTC, seong-hun commented
fl이 설마 Feedback Linearization? ㅋㅋ

2021-06-16 13:39 UTC, hnlee77 commented
> fl이 설마 Feedback Linearization? ㅋㅋ

네 맞슴다! 너무 길어서..ㅎㅎ

2021-06-17 15:34 UTC, JinraeKim commented
> 네 맞슴다! 너무 길어서..ㅎㅎ

나중에 PR 검색을 위해 제목만 수정했습니다 (fl이라고 찾을 것 같진 않아서 ㅎㅎ).

2021-06-17 17:37 UTC, seong-hun requested changes
* [이 파일](https://github.com/fdcl-ftc/fault-tolerant-control/blob/a405cd5d0cd359976314038fe6c29cf77668450b/test/feedbacklinearization.py)은 이전에 쓰던 템플릿에서 이름이 바뀐걸로 되어 있군요.. 의도한 건가요?
* 새로운 Fym 버전에 맞추어서 조금 수정을 해야할 필요가 있어 보이네요.

2021-06-18 03:36 UTC, hnlee77 commented
> * [이 파일](https://github.com/fdcl-ftc/fault-tolerant-control/blob/a405cd5d0cd359976314038fe6c29cf77668450b/test/feedbacklinearization.py)은 이전에 쓰던 템플릿에서 이름이 바뀐걸로 되어 있군요.. 의도한 건가요?

앗 이걸 의도한 것은 아니고 이전 템플릿 파일은 필요없어서 삭제하고, 이것은 `fl controller`를 사용해서 새로 만든 테스트파일이에요.

> * 새로운 Fym 버전에 맞추어서 조금 수정을 해야할 필요가 있어 보이네요.

앗 그렇군요! 수정하도록 하겠습니다.

2021-06-18 03:55 UTC, seong-hun commented
> 앗 이걸 의도한 것은 아니고 이전 템플릿 파일은 필요없어서 삭제하고, 이것은 `fl controller`를 사용해서 새로 만든 테스트파일이에요.

음 그럼 지금은 커밋이 renamed로 되어 있어서.. 이거 어캐 고쳐야 할 듯ㅠ

2021-06-18 04:37 UTC, hnlee77 commented
이거 왜 이렇게 된건지 모르겠는데 어떻게 수정하죠?..

2021-06-18 04:43 UTC, hnlee77 commented
이거 삭제하고 다시 추가해도 이렇게 뜨는데...

2021-06-18 05:03 UTC, seong-hun commented
> 이거 삭제하고 다시 추가해도 이렇게 뜨는데...
ㅠ 내가 함 테스트 해볼게

2021-06-18 05:18 UTC, seong-hun commented
이상하네 로컬 깃에서는 그냥 새로운 파일로 뜨는데 깃헙에서는 file name changed라고 뜨다니;;

로컬에서 확인해보면 새로운 파일이 맞는 것 같으니 넘어가도 될 것 같슴다...

2021-06-18 05:24 UTC, seong-hun commented
에러가 나는데요?
```bash
Traceback (most recent call last):
  File "/Users/seong-hun/workspace/github/ftc/fault-tolerant-control/test/feedbacklinearization.py", line 276, in <module>
    exp1_plot()
  File "/Users/seong-hun/workspace/github/ftc/fault-tolerant-control/test/feedbacklinearization.py", line 197, in exp1_plot
    plt.gcf().supylabel("FDI")
AttributeError: 'Figure' object has no attribute 'supylabel'
```

2021-06-18 06:27 UTC, hnlee77 commented
> 에러가 나는데요?
> 
> ```shell
> Traceback (most recent call last):
>   File "/Users/seong-hun/workspace/github/ftc/fault-tolerant-control/test/feedbacklinearization.py", line 276, in <module>
>     exp1_plot()
>   File "/Users/seong-hun/workspace/github/ftc/fault-tolerant-control/test/feedbacklinearization.py", line 197, in exp1_plot
>     plt.gcf().supylabel("FDI")
> AttributeError: 'Figure' object has no attribute 'supylabel'
> ```

오잉??? 저는 안나는데요?!? 혹시 matplotlib업데이트 한번 하고 다시 해주시겠어요??

2021-06-18 06:30 UTC, seong-hun commented
> 오잉??? 저는 안나는데요?!? 혹시 matplotlib업데이트 한번 하고 다시 해주시겠어요??

띠용?ㅋㅋㅋ 저는 3.4.2로 최신 버전입니다..

2021-06-18 06:30 UTC, hnlee77 commented
에에?? 저도인데... 뭘까요 이건?...ㅋㅋㅋㅋㅋ

2021-06-18 07:10 UTC, seong-hun commented
내 conda env가 이상했어 ㅠㅠ matplotlib 3.4.2 가 pip로 깔려있는데, 경로 우선순위가 conda 인가봐.. 근데 conda 공식 패키지로는 matplotlib 3.4.2 가 python 3.9 를 지원 안해서 conda-forge에서 버전 지정해서 깔아줘야함..ㅎ conda env 밀고 다시 설치하니까 잘 된다

2021-06-18 07:27 UTC, hnlee77 commented
> 내 conda env가 이상했어 ㅠㅠ matplotlib 3.4.2 가 pip로 깔려있는데, 경로 우선순위가 conda 인가봐.. 근데 conda 공식 패키지로는 matplotlib 3.4.2 가 python 3.9 를 지원 안해서 conda-forge에서 버전 지정해서 깔아줘야함..ㅎ conda env 밀고 다시 설치하니까 잘 된다

아하 파이썬과 호환이 문제였군!! 굳굳 ㅋㅋㅋ

2021-06-18 08:22 UTC, seong-hun commented
[`pr79-skim`](https://github.com/fdcl-ftc/fault-tolerant-control/tree/pr79-skim)에 적당히 손 본 코드를 올려두었습니다. `git diff` 등을 통해서 필요한 부분을 취해서 쓰면 좋을 것 같습니다.

2021-06-18 11:21 UTC, hnlee77 commented
> [`pr79-skim`](https://github.com/fdcl-ftc/fault-tolerant-control/tree/pr79-skim)에 적당히 손 본 코드를 올려두었습니다. `git diff` 등을 통해서 필요한 부분을 취해서 쓰면 좋을 것 같습니다.

네 알겠습니다! 감사합니다.

2021-06-21 03:48 UTC, hnlee77 commented
@seong-hun 반영했습니다.

2021-06-22 13:27 UTC, seong-hun approved these changes

2021-06-22 13:36 UTC, merged