Add calculate_recovery_rate
fdcl-ftc/fault-tolerant-control pull request #83
Opened 2021-06-16 03:47 UTC by JinraeKim

Resolve #74.

회복률 계산 함수를 작성함.
- 아무 형태의 np.ndarray 를 받아서, 각 원소의 절대값이 주어진 `threshold` 보다 작거나 같으면 성공으로 취급

- See `ftc/evaluate/evaluate.py`.
- Code example
```python3
    errors = np.array([
        [1, 2],
        [2, 3],
        [0, 1],
    ])
    threshold = 1.0
    recovery_rate = calculate_recovery_rate(errors, threshold=threshold)
    print(recovery_rate)
```

2021-06-16 09:05 UTC, seong-hun commented
다음 구문에 비해 장점이 있나요? 에러들이라 하면 굉장히 큰 행렬이지 싶은데, 행렬 크기가 커질수록 Numpy 메소드를 쓰는게 C보다 빠르다고 해서요.
```python
np.average(errors <= threshold)
```

2021-06-16 09:13 UTC, JinraeKim commented
> 다음 구문에 비해 장점이 있나요? 에러들이라 하면 굉장히 큰 행렬이지 싶은데, 행렬 크기가 커질수록 Numpy 메소드를 쓰는게 C보다 빠르다고 해서요.
> 
> ```python
> np.average(errors <= threshold)
> ```

별 의미는 없습니다. 저 함수를 몰랐습니다.
훨씬 깔끔하고 좋네요 (걍 줄짜리 함수가 되었군요 ㅎㅎ;)

2021-06-16 09:16 UTC, seong-hun requested changes

2021-06-16 09:16 UTC, seong-hun commented on ftc/evaluate/evaluate.py
> +    recovery_rate = np.average(errors <= threshold)
```suggestion
    recovery_rate = np.average(np.abs(errors) <= threshold)
```

2021-06-16 09:16 UTC, seong-hun commented on ftc/evaluate/evaluate.py
> +    recovery_rate = np.average(errors <= threshold)
컴퓨터 처리 과정에서 <= 보다 < 가 빨랐던거 같은데 꼭 <=를 쓰는 이유가 있을까요?

2021-06-16 09:34 UTC, JinraeKim commented on ftc/evaluate/evaluate.py
> +    recovery_rate = np.average(errors <= threshold)
ㅇㅋ

2021-06-17 02:08 UTC, JinraeKim commented
@seong-hun 위의 change request 전에 커밋을 넣어서 해결이 되었는데, 여전히 `1 change requested` 라는 문구가 나옵니다. 이거 어떻게 해결하는지 아시나요?

2021-06-17 02:10 UTC, seong-hun approved these changes

2021-06-17 02:10 UTC, seong-hun commented
> @seong-hun 위의 change request 전에 커밋을 넣어서 해결이 되었는데, 여전히 `1 change requested` 라는 문구가 나옵니다. 이거 어떻게 해결하는지 아시나요?

제가 requested change를 승인해야 하나봐요... 확실친 않은데 그렇게 하니까 뭔가 해결된 것 같은데?

2021-06-17 03:06 UTC, JinraeKim commented
> 제가 requested change를 승인해야 하나봐요... 확실친 않은데 그렇게 하니까 뭔가 해결된 것 같은데?

그런듯 ㅋㅋㅋ 감삼다 ㅎ

2021-06-17 07:47 UTC, merged