Adaptive SMC 및 SMC
fdcl-ftc/fault-tolerant-control pull request #96
Opened 2021-06-25 09:17 UTC by miaerosae

controller 및 fault에 대해 test한 파일입니당!

1. Adaptive SMC & 시나리오2
 
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/80808711/123400635-f1242300-d5e0-11eb-8181-78974be26dad.png">

약간 rotor input이 좀 이상하네요 허허..

2. SMC & 시나리오 1

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/80808711/123400806-1c0e7700-d5e1-11eb-83f5-6b4303e30cd6.png">

시나리오 2는 돌아가기도 하고 안돌아가기도 하는 모습을 보입니다

2021-06-25 09:37 UTC, miaerosae commented
1번에서 조건이 3초에 rotor 0 고장, 6초에 rotor 2 고장인데 input 및 response가 이상하게 들어가는 것 같습니다

2021-06-26 00:59 UTC, seong-hun commented
혹시 어떤 스크립트를 돌려보면 되나요?

2021-06-26 01:06 UTC, seong-hun commented
`test/fault_ASMC.py`와 `test/fault_fASMC.py` 같네요.
그런데 코드를 보면 고장이 발생하면 Constrained CA를 쓰는데, 의도된 건가요? 이 모듈은 @hnlee77 가 짠 것인데 매시각 최적화 솔버를 돌리기 때문에 variable step 적분에서는 적분 민감도에 따라 다르겠지만 SMC의 경우 민감해서, step을 굉장히 많이 테스트 하기 때문에 느릴 수 밖에 없을 것 같아요.

2021-06-27 04:22 UTC, miaerosae commented
> `test/fault_ASMC.py`와 `test/fault_SMC.py` 같네요.
> 그런데 코드를 보면 고장이 발생하면 Constrained CA를 쓰는데, 의도된 건가요? 이 모듈은 @hnlee77 가 짠 것인데 매시각 최적화 솔버를 돌리기 때문에 variable step 적분에서는 적분 민감도에 따라 다르겠지만 SMC의 경우 민감해서, step을 굉장히 많이 테스트 하기 때문에 느릴 수 밖에 없을 것 같아요.

앗 그렇군요. 기존 CA를 썼을 경우 저번 회의에서 언급된 것과 같이 로터 인풋이 조금 이상한 경우가 있어 제대로 제어가 되지 않는 것 같아 Constrained CA를 사용하였습니다. 
그냥 CA를 사용하면 아래와 같은 인풋이 들어갑니다
오빠가 actuator.py 고치신 것도 반영한 결과입니다,..

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/80808711/123532723-aaead300-d74a-11eb-9ef6-cd7a96243c78.png">

2021-06-28 08:47 UTC, seong-hun commented
오줌싸는 꼬마 천사 동상 같아...

2021-06-30 08:15 UTC, miaerosae commented
adaptive SMC + CA

rotor 1 fault at t=3
rotor 3 fault at t=6

계산시간 10초(ㅜ)

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/80808711/123926339-c06c3100-d9c6-11eb-8a29-03ff37208fc7.png">

야호 @hnlee77 감사합니다!!!!

2021-07-29 04:26 UTC, hnlee77 commented
요거 rebase 부탁해요~

2021-07-29 07:41 UTC, hnlee77 requested changes
`ftc/models/fixedWing.py`가 함께 커밋에 들어가있네요~ 이거 삭제해야 하는거죠?

2021-07-29 07:42 UTC, miaerosae commented
> `ftc/models/fixedWing.py`가 함께 커밋에 들어가있네요~ 이거 삭제해야 하는거죠?

넵 맞습니다!! 필요없는 아이입니다!

2021-07-29 07:53 UTC, hnlee77 commented on test/fault_ASMC.py
> +class ActuatorDynamcs(BaseSystem):
`test/ASMC.py` 파일이 있고, `test/fault_ASMC.py` 가 따로 있는데 다른 역할을 하는 걸까요?? 둘 다 필요한 파일인가요?

2021-07-29 07:53 UTC, hnlee77 commented on test/fault_SMC.py
> +    plt.show()
이 부분도 Plotting 모듈을 사용하도록 바꿔도 될까요?

2021-07-29 07:53 UTC, hnlee77 commented on test/fault_SMC.py
> +        self.detection_time = [[] for _ in range(len(self.actuator_faults))]
요것도 바꿔야 겠네요~

2021-07-29 07:54 UTC, miaerosae commented on test/fault_ASMC.py
> +class ActuatorDynamcs(BaseSystem):
ASMC는 고장 정보 없이 컨트롤러 테스트이고, fault_ASMC는 고장을 포함한 것입니다..!

2021-07-29 07:54 UTC, miaerosae commented on test/fault_SMC.py
> +    plt.show()
앗 너무 감사합니다.. 너무 예전꺼라 Plotting model이 없을 때였던 것 같ㅇ아요..

2021-07-29 07:55 UTC, miaerosae commented on test/fault_SMC.py
> +        self.detection_time = [[] for _ in range(len(self.actuator_faults))]
detection time을 말씀하시는건가요..? 저것은 그 fault 템플릿에서 그대로 가져온 것인데, 사실 잘 몰라서 그냥 내버려 두긴 했습니다..!

2021-07-29 07:55 UTC, hnlee77 commented on test/fault_ASMC.py
> +class ActuatorDynamcs(BaseSystem):
아 그렇군요~ 알겠습니다!

2021-07-29 07:56 UTC, hnlee77 commented on test/fault_SMC.py
> +        self.detection_time = [[] for _ in range(len(self.actuator_faults))]
맞아요 이부분도 예전것이라서 바꾸면 될 것 같아요 ㅋㅋㅋ

2021-07-29 08:02 UTC, hnlee77 commented on test/fault_ASMC.py
> +class ActuatorDynamcs(BaseSystem):
아 그렇다면 `test/fault_ASMC.py`에서 결국 fault를 주지 않으면 같은 결과가 나오는 것이겠죠?

2021-07-29 08:10 UTC, miaerosae commented on test/fault_ASMC.py
> +class ActuatorDynamcs(BaseSystem):
앗,,! 그렇네요 그렇습니다!

2021-07-29 08:10 UTC, miaerosae commented on test/fault_SMC.py
> +        self.detection_time = [[] for _ in range(len(self.actuator_faults))]
넵 알겠습니다!

2021-07-29 08:18 UTC, hnlee77 commented on test/fault_ASMC.py
> +class ActuatorDynamcs(BaseSystem):
그렇다면 `test/ASMC.py`는 삭제하고, 나머지 test 파일들의 이름을 `test/ASMC.py`, `test/SMC.py`로 통일하는 것이 어떨까요?

2021-08-12 13:32 UTC, miaerosae commented
너무 늦게 수정해서 죄송합니다..! 다 수정했습니다

2021-08-13 04:06 UTC, hnlee77 commented
이거 혹시 돌려본걸까요? 안돌아가네요 ㅠ

2021-08-13 04:36 UTC, hnlee77 approved these changes

2021-08-13 04:37 UTC, merged