Fix scenario-1 to meet modified FDI
fdcl-ftc/fault-tolerant-control pull request #98
Opened 2021-06-28 04:45 UTC by hnlee77

변화된 `ftc`, `fym` 모듈에 따라 코드를 수정하였습니다.
### Results
- 여러개의 actuator 고장에 따른 FDI 모듈 정상작동 확인
- plotting 모듈 정상 작동 확인

2021-06-28 04:52 UTC, seong-hun requested changes

2021-06-28 04:52 UTC, seong-hun commented on test/scenario_a_1.py
>          rotors_cmd, W, rotors = self._get_derivs(t, mult_states, What)
`_get_derive`라는 메소드는 없어도 될 것 처럼 보입니다.

2021-06-28 04:52 UTC, seong-hun commented on test/scenario_a_1.py
> +    loggerpath = "./data.h5"
`./` 는 왜 넣는 것인가요?

2021-06-28 04:52 UTC, seong-hun commented on test/scenario_a_1.py
> +        rotors = _rotors.copy()
이제 `_rotors`는 필요 없어 보입니다.

2021-06-28 04:52 UTC, seong-hun commented on test/scenario_a_1.py
>          self.CCA = ConstrainedCA(self.plant.mixer.B)
근데 우리 시나리오 정의가 시나리오1에서 Constrained CA를 쓰도록 바뀌었나요? 어디가면 볼 수 있죠?

2021-06-28 04:52 UTC, seong-hun commented on test/scenario_a_1.py
>                  self.detection_time[len(fault_index) - 1] == [t]
이제 delay 등으로 사전에 감지 시각을 알 수 있으므로 이 부분은 빼고, delay 정보 등을 통해서 초기화 할 때 계산하는게 어떨까요?

2021-06-28 08:45 UTC, seong-hun requested changes

2021-06-28 08:45 UTC, seong-hun commented on test/scenario_a_1.py
> +            LoE(time=6, index=2, level=0.),  # scenario b
```python
# scenario a, b
```
주석이 헷갈리네여

2021-06-28 08:45 UTC, seong-hun commented on test/scenario_a_1.py
> +    env.logger = fym.Logger("data/data.h5")
이게 윈도우에서도 돌아 가던가요?? WSL 말고

2021-06-28 08:45 UTC, seong-hun commented on test/scenario_a_1.py
> +    env.logger = fym.Logger("data/data.h5")
아마 안돌아갈텐데..

2021-06-28 08:45 UTC, seong-hun commented on test/scenario_a_1.py
> +        self.detection_time = [[self.actuator_faults[i].time + self.fdi.delay] for i in range(len(self.actuator_faults))]
```suggestion
        self.detection_time = [fault.time + self.fdi.delay for fault in self.actuator_faults]
```

이거 `data.h5`에 info 라던지로 저장이 되고 있나요?

2021-06-29 06:46 UTC, hnlee77 reviewed
아 이거 submit review를 하지 않으면 comment에 답글을 달아도 보이지가 않는 것인가요?

2021-06-29 06:46 UTC, hnlee77 commented on test/scenario_a_1.py
> +            LoE(time=6, index=2, level=0.),  # scenario b
single fault가 scenario a, 두번째 고장이 scenario b에 해당하기 때문에 각각 따로 작성했습니다. 이것이 헷갈리는 부분이 맞나요??

2021-06-29 06:46 UTC, hnlee77 commented on test/scenario_a_1.py
> +    env.logger = fym.Logger("data/data.h5")
윈도우라면 vscode 같은 것을 말씀하시는 건가요?! 저는 wsl만 사용해서 잘 모르겠습니다.. `fym.logging`으로 모듈을 사용해야 하는 것인가요??

2021-06-29 06:46 UTC, hnlee77 commented on test/scenario_a_1.py
> +        self.detection_time = [[self.actuator_faults[i].time + self.fdi.delay] for i in range(len(self.actuator_faults))]
추후에 값을 사용할 수 있도록 info로 저장하는 것으로 수정하였습니다.

2021-06-29 06:50 UTC, seong-hun commented on test/scenario_a_1.py
> +            LoE(time=6, index=2, level=0.),  # scenario b
그냥 내가 시나리오 정의를 헷갈려하는 것 같습니다.. 참고 페이지 만들면 될듯!

2021-06-29 06:51 UTC, seong-hun commented on test/scenario_a_1.py
> +    env.logger = fym.Logger("data/data.h5")
`"data/data.h5"` 처럼 쓰는 것 말하는건데.. 이게 윈도우는 `"data\data.h5"`로 써야 했던것 같아서.. Python 버전 올라가면서 이런거 좀 바뀌었으려나? 나는 그냥 `pathlib` 쓰긴 하는데..

2021-06-29 07:01 UTC, hnlee77 commented on test/scenario_a_1.py
> +            LoE(time=6, index=2, level=0.),  # scenario b
알겠습니다!

2021-06-29 07:13 UTC, hnlee77 commented on test/scenario_a_1.py
> +    env.logger = fym.Logger("data/data.h5")
아 그런 이슈가 있을 수 있겠군요.. 맞아요 윈도우는 문제가 있을 듯. 그냥 기본 경로로 저장하도록 수정했습니다.

2021-06-30 07:05 UTC, seong-hun approved these changes

2021-06-30 07:06 UTC, merged