Fix-CA
fdcl-ftc/fault-tolerant-control pull request #99
Opened 2021-06-28 05:36 UTC by hnlee77

Resolved #94.

현재 CA 모듈이 B의 참조값을 바꿔버리는 현상이 발생함.
이를 방지하도록 `bug` 수정

2021-06-28 08:37 UTC, seong-hun approved these changes
여전히 CA 모듈은 뭔가 네이밍과 기능이 매치가 안되는군요..

2021-06-28 08:43 UTC, hnlee77 commented
> 여전히 CA 모듈은 뭔가 네이밍과 기능이 매치가 안되는군요..

앗 이부분을 완전히 잊고 있었군요.. 이것은 다시 이슈를 파서 수정하도록 하겠습니다!

2021-06-29 07:10 UTC, hnlee77 commented
CA 모듈이 allocator를 리턴하도록 수정함.

2021-06-29 07:40 UTC, seong-hun requested changes

2021-06-29 07:40 UTC, seong-hun commented on ftc/agents/CA.py
> +        return np.linalg.pinv(BB.dot(What))
이거 맞나요..? 테스트로 시나리오들 돌려보고 있죠...?ㅠ

2021-06-29 07:45 UTC, hnlee77 commented on ftc/agents/CA.py
> +        return np.linalg.pinv(BB.dot(What))
넵! 확인 했는데요! 문제가 있나요?..

2021-06-29 07:49 UTC, seong-hun commented on ftc/agents/CA.py
> +        return np.linalg.pinv(BB.dot(What))
```suggestion
        return np.linalg.pinv(BB)
```
이렇게 해야할 것 같아서... 아닌가..?

2021-06-29 08:08 UTC, hnlee77 commented on ftc/agents/CA.py
> +        return np.linalg.pinv(BB.dot(What))
죄송... 지금 0으로 모두 같은 값으로 나와서 그냥 넘어갈 뻔 했네요. 이게 맞아요!!

2021-06-29 08:13 UTC, seong-hun approved these changes

2021-06-29 08:27 UTC, merged